export const CHANNELS = {
  NAVIGATE: 'navigate',
  SET_ACTIVE_COLUMN: 'set-active-column',
  SET_COLUMN_VISIBLE: 'set-column-visible',
  GO_BACK: 'go-back',
  GO_FORWARD: 'go-forward',
  COMPOSE_POST: 'compose-post',
  CLOSE_COLUMN: 'close-column',
  REQUEST_ADD_ACCOUNT: 'request-add-account',
  REORDER_COLUMNS: 'reorder-columns',
  // Phase 8: shift the visible column window left/right (overflow rail ◀▶ buttons)
  SCROLL_COLUMNS: 'scroll-columns',
  RENDERER_READY: 'renderer-ready',
  NAV_STATE_CHANGED: 'nav-state-changed',
  COLUMN_LAYOUT: 'column-layout',
  ACCOUNTS_CHANGED: 'accounts-changed',
  ACCOUNTS_LIST: 'accounts-list',
  ACTIVE_CHANGED: 'active-changed',
  UNREAD_CHANGED: 'unread-changed',
  CHECK_FOR_UPDATES: 'check-for-updates',
  QUIT_AND_INSTALL: 'quit-and-install',
  UPDATE_STATUS: 'update-status',
  // Phase 7: AI 下書き（虎威ゲート + BYOK Gemini）
  SET_UNLOCK_KEY: 'set-unlock-key',
  CLEAR_UNLOCK_KEY: 'clear-unlock-key',
  SET_GEMINI_KEY: 'set-gemini-key',
  CLEAR_GEMINI_KEY: 'clear-gemini-key',
  CHECK_SUBSCRIPTION: 'check-subscription',
  GET_AI_STATE: 'get-ai-state',
  AI_STATE: 'ai-state',
  GENERATE_DRAFTS: 'generate-drafts',
  // AI パネル表示中はカラムの WebContentsView を隠してレンダラーのオーバーレイを前面に出す
  SET_AI_OVERLAY: 'set-ai-overlay',
} as const
